### PR TITLE
Documenting feature-sapic-integration

### PR DESCRIPTION
**Pull request by rkunnema**
Hi!

This documents the *current* status of the integration of SAPIC as if it were bug-free in a separate section on "Modelling Protocols with Processes".

Also it fixes the use of a deprecated flag to pandoc in the Makefile. (You might need to update your pandoc accordingly, not sure. Pandoc 2.3.1, the version I have, refuses to compile with the old flag, so if updating is not an option, we need to add a version check to the Makefile.)

Cheers, Robert

### CODE REVIEW

**Comment by rkunnema** [comment]
Added documentation for features supported in https://github.com/tamarin-prover/tamarin-prover/pull/319/commits/cc35a511234bffa4eb15fa298ff3cf2792b3f429.

**Comment by rkunnema** [comment]
Bump.

**Comment by jdreier** [comment]
is `reliable-channel`an equational theory, as it is currently described in that part?

**Comment by rkunnema** [comment]
You are right, it is not, however, it is invoked similarly: `builtins: reliable-channels`. What do you think, should we change the headline: "Built-in message theories" to "Built-in message theories and other built-in features"?

**Comment by jdreier** [comment]
I find it confusing there, as it also seems to be SAPIC-specific. Why not move it to the chapter describing SAPIC input?

**Comment by rkunnema** [comment]
(Imho) there should be one place that lists everything that can go after `builtins`. There are also translation-specific options:
```
options: translation-progress
```

We've discussed this question (are reliable channels an option or a builtin?) in the mattermost group and the consensus was to have this a built-in because it has to do with messages. We can open up this discussion again (I am okay with either way) but in any case I prefer that the manual is consistent with how these things are categorised.

Low-effort option:  make the link to the process calculus more explicit? See 6169ad052ada70e07bfb0b93214cf7d9430089b7

**Comment by jdreier** [comment]
Which mattermost group?

What happens if you do not use SAPIC and you activate reliable channels?

**Comment by rkunnema** [comment]
> Which mattermost group?

An invitation is on the way. 

> What happens if you do not use SAPIC and you activate reliable channels?

Nothing ATM. But it could be useful to have it in msrs.

**Comment by katrielalex** [comment]
> Nothing ATM. But it could be useful to have it in msrs.

If it's easy, it might be nice to make this an error. Otherwise people might see the builtin and assume that straight-Tamarin is doing something it's not, and then get confused.

**Comment by rkunnema** [comment]
Good idea. It was easy to implement, it will part of the next PR.

**Pull request merged**
